#ifndef ALLINCLUDE_H
#define ALLINCLUDE_H
#include <QMap>
#include <QMessageBox>
#include <QSqlDatabase>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSqlQuery>
#include <QSqlError>
#include <QMouseEvent>
#include <QLineEdit>
#include <QLabel>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QFileDialog>
#include <QDataWidgetMapper>
#include <QDebug>
#include <QVBoxLayout>
#include <QListWidget>
#include <QMenuBar>
#include <QComboBox>
#include <QMainWindow>
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QSqlTableModel>
#include <QTableView>
#include <QSqlRelationalTableModel>
#include <QSqlRelationalDelegate>
#include <QSqlQueryModel>
#include <QModelIndex>
#include <QTextEdit>
#include <QDateTime>
#include <QSqlRecord>
#endif // ALLINCLUDE_H
